### ISSUE TITLE
CocoaPods version doesn't understand inherit directive

### ISSUE THREAD

**Issue by flyashi** [bitrise-io/build.issues#26]
# Bitrise Build Issue Report template

## Description of the issue

CocoaPods file:
```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'owalMobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for owalMobile
  pod 'Firebase/Messaging'

  target 'owalMobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

## Environment:

__Where did the issue happen?__

_If on Bitrise.io: which stack? If not on Bitrise.io: on what operating system? (Plus any other information you can share)_
Xcode 7.3.1, on OS X 10.11 (El Capitan) - LTS Stack

__Which build Step causes the issue and which version of the step?__
Script step. Contents:
`cd ios; pod install`

## Reproducibility

- _Does a "Rebuild" help? (You can trigger a rebuild from the Build's page, by clicking the "Rebuild" button in the top right corner of a finished build)_ : NO
- _Does a rebuild without caches help? (You can remove the `Cache:Pull` and `Cache:Push` steps temporarily to not to use the cache, or [you can *delete all the caches* on the `Settings` tab of the app](https://bitrise-io.github.io/devcenter/caching/about-caching/#downloading-and-deleting-caches)._ : NO
- _If it's an issue which happens sporadically, what's the frequency? (e.g. Once a day ; about x% of the builds)_ : 100%
- _Does upgrading the build Step to the latest version help?_ : NO
- _When did the issue start?_ :
When we checked in that Podfile

### Linux/Android stack builds

_Can it be reproduced by running the build locally, **after doing a clean git clone (git clone the repository, into a new directory, somewhere on your Mac/PC)** and running the build from there with the Bitrise CLI ( https://www.bitrise.io/cli )? If no, can it be reproduced with Docker (using the same docker images / environment we use on bitrise.io)? Related guide: http://blog.bitrise.io/2016/08/08/debug-your-android-linux-builds-locally-with-docker.html ._

### Other stacks

_Can it be reproduced by running the build locally with our CLI ( https://www.bitrise.io/cli ), **after doing a clean git clone (git clone the repository, into a new directory, somewhere on your Mac/PC)** and running the build from there with the CLI ( https://www.bitrise.io/cli )?_

Locally I'm running a newer version of CocoaPods.

## Build log

Relevant section:
```
+------------------------------------------------------------------------------+
| (4) pod install                                                              |
+------------------------------------------------------------------------------+
| id: script                                                                   |
| version: 1.1.3                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: bash                                                                |
| time: 2016-12-08T09:45:20-08:00                                              |
+------------------------------------------------------------------------------+
|                                                                              |
+ echo 'Hello World!'
Hello World!
+ cd ios
+ pod install

[!] Invalid `Podfile` file: undefined method `inherit!' for #<Pod::Podfile:0x007fa06b3a2420>. Updating CocoaPods might fix the issue.

 #  from /Users/vagrant/git/ios/Podfile:12
 #  -------------------------------------------
 #    target 'owalMobileTests' do
 >      inherit! :search_paths
 #      # Pods for testing
 #  -------------------------------------------
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | pod install (exit code: 1)                                    | 3.92 sec |
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-io/steps-script/issues             |
| Source: https://github.com/bitrise-io/steps-script                           |
+---+---------------------------------------------------------------+----------+
```

**Comment by viktorbenei** [comment]
Thanks for creating the report @flyashi !

A quick note, before suggesting a solution: to run `pod install` please use the `Run CocoaPods install` step instead of running `pod install` in a Script step, as that step has built in features for detecting the required CocoaPods version - read from the `Podfile.lock` - and it installs the right CocoaPods version before running `pod install`.

In your case that alone won't fix the issue, due to a breaking change between CocoaPods 0.39 and 1.x which now require separate cocoapods specs. In short this means that if the local cocoapods spec was created by and for 0.39 it will take a really long time to switch it to the 1.x format.

Due to this, if you want to use the Xcode 7.3 stack, which has CocoaPods 0.39 preinstalled, you should use CocoaPods 0.39 on your Mac too, and do not upgrade to CocoaPods 1.x . If you want to use CocoaPods 1.x you should use an Xcode stack which has a CocoaPods 1.x version preinstalled (all the Xcode 8 ones have CocoaPods 1.x installed, but the Xcode 6 and 7 ones are 0.39).

You can find more information about the issue, and other solution recommendations here: https://github.com/bitrise-io/build.issues/issues/16#issuecomment-264700459
